DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS joke;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  nickname TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  joke_balance INTEGER DEFAULT 0,
  is_mod BOOLEAN DEFAULT FALSE
);

CREATE TABLE joke (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  author_nickname TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  ratings DOUBLE DEFAULT 0.0,
  number_of_rating INTEGER DEFAULT 0,
  FOREIGN KEY (author_id) REFERENCES user (id)
);